mixed-port: 7890
allow-lan: true
mode: rule
ipv6: true

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053

  nameserver:
    # Google
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844

    # Cloudflare
    - 1.1.1.1
    - 1.0.0.1
    - 2606:4700:4700::1111
    - 2606:4700:4700::1001

    # Quad9
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

    # OpenDNS
    - 208.67.222.222
    - 208.67.220.220
    - 2620:119:35::35
    - 2620:119:53::53

    # Verisign
    - 64.6.64.6
    - 64.6.65.6

  fallback:
    # DoH
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.quad9.net/dns-query


proxy-providers:
  mysub:
    type: http
    url: "https://raw.githubusercontent.com/monomono98/FREE-sub/refs/heads/main/sub.txt"
    interval: 3600
    path: ./providers/mysub.yaml


proxy-groups:
  - name: AUTO
    type: select
    use:
      - mysub


rules:
  - MATCH,AUTO
